CREATE TABLE IF NOT EXISTS image (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHARACTER(36) UNIQUE
);

CREATE TABLE IF NOT EXISTS tag (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(64) UNIQUE
);